export const countriesInfo = [
    {
        name: "Andorra",
        countryCode: "AD",
        phone: "376",
        currency: "EUR",
    },
    {
        name: "United Arab Emirates",
        countryCode: "AE",
        phone: "971",
        currency: "AED",
    },
    {
        name: "Afghanistan",
        countryCode: "AF",
        phone: "93",
        currency: "AFN",
    },
    {
        name: "Antigua and Barbuda",
        countryCode: "AG",
        phone: "+1-268",
        currency: "XCD",
    },
    {
        name: "Anguilla",
        countryCode: "AI",
        phone: "+1-264",
        currency: "XCD",
    },
    {
        name: "Albania",
        countryCode: "AL",
        phone: "355",
        currency: "ALL",
    },
    {
        name: "Armenia",
        countryCode: "AM",
        phone: "374",
        currency: "AMD",
    },
    {
        name: "Angola",
        countryCode: "AO",
        phone: "244",
        currency: "AOA",
    },
    {
        name: "Antarctica",
        countryCode: "AQ",
        phone: "",
        currency: "",
    },
    {
        name: "Argentina",
        countryCode: "AR",
        phone: "54",
        currency: "ARS",
    },
    {
        name: "American Samoa",
        countryCode: "AS",
        phone: "+1-684",
        currency: "USD",
    },
    {
        name: "Austria",
        countryCode: "AT",
        phone: "43",
        currency: "EUR",
    },
    {
        name: "Australia",
        countryCode: "AU",
        phone: "61",
        currency: "AUD",
    },
    {
        name: "Aruba",
        countryCode: "AW",
        phone: "297",
        currency: "AWG",
    },
    {
        name: "Aland Islands",
        countryCode: "AX",
        phone: "+358-18",
        currency: "EUR",
    },
    {
        name: "Azerbaijan",
        countryCode: "AZ",
        phone: "994",
        currency: "AZN",
    },
    {
        name: "Bosnia and Herzegovina",
        countryCode: "BA",
        phone: "387",
        currency: "BAM",
    },
    {
        name: "Barbados",
        countryCode: "BB",
        phone: "+1-246",
        currency: "BBD",
    },
    {
        name: "Bangladesh",
        countryCode: "BD",
        phone: "880",
        currency: "BDT",
    },
    {
        name: "Belgium",
        countryCode: "BE",
        phone: "32",
        currency: "EUR",
    },
    {
        name: "Burkina Faso",
        countryCode: "BF",
        phone: "226",
        currency: "XOF",
    },
    {
        name: "Bulgaria",
        countryCode: "BG",
        phone: "359",
        currency: "BGN",
    },
    {
        name: "Bahrain",
        countryCode: "BH",
        phone: "973",
        currency: "BHD",
    },
    {
        name: "Burundi",
        countryCode: "BI",
        phone: "257",
        currency: "BIF",
    },
    {
        name: "Benin",
        countryCode: "BJ",
        phone: "229",
        currency: "XOF",
    },
    {
        name: "Saint Barthelemy",
        countryCode: "BL",
        phone: "590",
        currency: "EUR",
    },
    {
        name: "Bermuda",
        countryCode: "BM",
        phone: "+1-441",
        currency: "BMD",
    },
    {
        name: "Brunei",
        countryCode: "BN",
        phone: "673",
        currency: "BND",
    },
    {
        name: "Bolivia",
        countryCode: "BO",
        phone: "591",
        currency: "BOB",
    },
    {
        name: "Bonaire, Saint Eustatius and Saba",
        countryCode: "BQ",
        phone: "599",
        currency: "USD",
    },
    {
        name: "Brazil",
        countryCode: "BR",
        phone: "55",
        currency: "BRL",
    },
    {
        name: "Bahamas",
        countryCode: "BS",
        phone: "+1-242",
        currency: "BSD",
    },
    {
        name: "Bhutan",
        countryCode: "BT",
        phone: "975",
        currency: "BTN",
    },
    {
        name: "Bouvet Island",
        countryCode: "BV",
        phone: "",
        currency: "NOK",
    },
    {
        name: "Botswana",
        countryCode: "BW",
        phone: "267",
        currency: "BWP",
    },
    {
        name: "Belarus",
        countryCode: "BY",
        phone: "375",
        currency: "BYN",
    },
    {
        name: "Belize",
        countryCode: "BZ",
        phone: "501",
        currency: "BZD",
    },
    {
        name: "Canada",
        countryCode: "CA",
        phone: "1",
        currency: "CAD",
    },
    {
        name: "Cocos Islands",
        countryCode: "CC",
        phone: "61",
        currency: "AUD",
    },
    {
        name: "Democratic Republic of the Congo",
        countryCode: "CD",
        phone: "243",
        currency: "CDF",
    },
    {
        name: "Central African Republic",
        countryCode: "CF",
        phone: "236",
        currency: "XAF",
    },
    {
        name: "Republic of the Congo",
        countryCode: "CG",
        phone: "242",
        currency: "XAF",
    },
    {
        name: "Switzerland",
        countryCode: "CH",
        phone: "41",
        currency: "CHF",
    },
    {
        name: "Ivory Coast",
        countryCode: "CI",
        phone: "225",
        currency: "XOF",
    },
    {
        name: "Cook Islands",
        countryCode: "CK",
        phone: "682",
        currency: "NZD",
    },
    {
        name: "Chile",
        countryCode: "CL",
        phone: "56",
        currency: "CLP",
    },
    {
        name: "Cameroon",
        countryCode: "CM",
        phone: "237",
        currency: "XAF",
    },
    {
        name: "China",
        countryCode: "CN",
        phone: "86",
        currency: "CNY",
    },
    {
        name: "Colombia",
        countryCode: "CO",
        phone: "57",
        currency: "COP",
    },
    {
        name: "Costa Rica",
        countryCode: "CR",
        phone: "506",
        currency: "CRC",
    },
    {
        name: "Cuba",
        countryCode: "CU",
        phone: "53",
        currency: "CUP",
    },
    {
        name: "Cabo Verde",
        countryCode: "CV",
        phone: "238",
        currency: "CVE",
    },
    {
        name: "Curacao",
        countryCode: "CW",
        phone: "599",
        currency: "ANG",
    },
    {
        name: "Christmas Island",
        countryCode: "CX",
        phone: "61",
        currency: "AUD",
    },
    {
        name: "Cyprus",
        countryCode: "CY",
        phone: "357",
        currency: "EUR",
    },
    {
        name: "Czechia",
        countryCode: "CZ",
        phone: "420",
        currency: "CZK",
    },
    {
        name: "Germany",
        countryCode: "DE",
        phone: "49",
        currency: "EUR",
    },
    {
        name: "Djibouti",
        countryCode: "DJ",
        phone: "253",
        currency: "DJF",
    },
    {
        name: "Denmark",
        countryCode: "DK",
        phone: "45",
        currency: "DKK",
    },
    {
        name: "Dominica",
        countryCode: "DM",
        phone: "+1-767",
        currency: "XCD",
    },
    {
        name: "Dominican Republic",
        countryCode: "DO",
        phone: "+1-809 and 1-829",
        currency: "DOP",
    },
    {
        name: "Algeria",
        countryCode: "DZ",
        phone: "213",
        currency: "DZD",
    },
    {
        name: "Ecuador",
        countryCode: "EC",
        phone: "593",
        currency: "USD",
    },
    {
        name: "Estonia",
        countryCode: "EE",
        phone: "372",
        currency: "EUR",
    },
    {
        name: "Egypt",
        countryCode: "EG",
        phone: "20",
        currency: "EGP",
    },
    {
        name: "Western Sahara",
        countryCode: "EH",
        phone: "212",
        currency: "MAD",
    },
    {
        name: "Eritrea",
        countryCode: "ER",
        phone: "291",
        currency: "ERN",
    },
    {
        name: "Spain",
        countryCode: "ES",
        phone: "34",
        currency: "EUR",
    },
    {
        name: "Ethiopia",
        countryCode: "ET",
        phone: "251",
        currency: "ETB",
    },
    {
        name: "Finland",
        countryCode: "FI",
        phone: "358",
        currency: "EUR",
    },
    {
        name: "Fiji",
        countryCode: "FJ",
        phone: "679",
        currency: "FJD",
    },
    {
        name: "Falkland Islands",
        countryCode: "FK",
        phone: "500",
        currency: "FKP",
    },
    {
        name: "Micronesia",
        countryCode: "FM",
        phone: "691",
        currency: "USD",
    },
    {
        name: "Faroe Islands",
        countryCode: "FO",
        phone: "298",
        currency: "DKK",
    },
    {
        name: "France",
        countryCode: "FR",
        phone: "33",
        currency: "EUR",
    },
    {
        name: "Gabon",
        countryCode: "GA",
        phone: "241",
        currency: "XAF",
    },
    {
        name: "United Kingdom",
        countryCode: "GB",
        phone: "44",
        currency: "GBP",
    },
    {
        name: "Grenada",
        countryCode: "GD",
        phone: "+1-473",
        currency: "XCD",
    },
    {
        name: "Georgia",
        countryCode: "GE",
        phone: "995",
        currency: "GEL",
    },
    {
        name: "French Guiana",
        countryCode: "GF",
        phone: "594",
        currency: "EUR",
    },
    {
        name: "Guernsey",
        countryCode: "GG",
        phone: "+44-1481",
        currency: "GBP",
    },
    {
        name: "Ghana",
        countryCode: "GH",
        phone: "233",
        currency: "GHS",
    },
    {
        name: "Gibraltar",
        countryCode: "GI",
        phone: "350",
        currency: "GIP",
    },
    {
        name: "Greenland",
        countryCode: "GL",
        phone: "299",
        currency: "DKK",
    },
    {
        name: "Gambia",
        countryCode: "GM",
        phone: "220",
        currency: "GMD",
    },
    {
        name: "Guinea",
        countryCode: "GN",
        phone: "224",
        currency: "GNF",
    },
    {
        name: "Guadeloupe",
        countryCode: "GP",
        phone: "590",
        currency: "EUR",
    },
    {
        name: "Equatorial Guinea",
        countryCode: "GQ",
        phone: "240",
        currency: "XAF",
    },
    {
        name: "Greece",
        countryCode: "GR",
        phone: "30",
        currency: "EUR",
    },
    {
        name: "South Georgia and the South Sandwich Islands",
        countryCode: "GS",
        phone: "",
        currency: "GBP",
    },
    {
        name: "Guatemala",
        countryCode: "GT",
        phone: "502",
        currency: "GTQ",
    },
    {
        name: "Guam",
        countryCode: "GU",
        phone: "+1-671",
        currency: "USD",
    },
    {
        name: "Guinea-Bissau",
        countryCode: "GW",
        phone: "245",
        currency: "XOF",
    },
    {
        name: "Guyana",
        countryCode: "GY",
        phone: "592",
        currency: "GYD",
    },
    {
        name: "Hong Kong",
        countryCode: "HK",
        phone: "852",
        currency: "HKD",
    },
    {
        name: "Heard Island and McDonald Islands",
        countryCode: "HM",
        phone: "",
        currency: "AUD",
    },
    {
        name: "Honduras",
        countryCode: "HN",
        phone: "504",
        currency: "HNL",
    },
    {
        name: "Croatia",
        countryCode: "HR",
        phone: "385",
        currency: "EUR",
    },
    {
        name: "Haiti",
        countryCode: "HT",
        phone: "509",
        currency: "HTG",
    },
    {
        name: "Hungary",
        countryCode: "HU",
        phone: "36",
        currency: "HUF",
    },
    {
        name: "Indonesia",
        countryCode: "ID",
        phone: "62",
        currency: "IDR",
    },
    {
        name: "Ireland",
        countryCode: "IE",
        phone: "353",
        currency: "EUR",
    },
    {
        name: "Israel",
        countryCode: "IL",
        phone: "972",
        currency: "ILS",
    },
    {
        name: "Isle of Man",
        countryCode: "IM",
        phone: "+44-1624",
        currency: "GBP",
    },
    {
        name: "India",
        countryCode: "IN",
        phone: "91",
        currency: "INR",
    },
    {
        name: "British Indian Ocean Territory",
        countryCode: "IO",
        phone: "246",
        currency: "USD",
    },
    {
        name: "Iraq",
        countryCode: "IQ",
        phone: "964",
        currency: "IQD",
    },
    {
        name: "Iran",
        countryCode: "IR",
        phone: "98",
        currency: "IRR",
    },
    {
        name: "Iceland",
        countryCode: "IS",
        phone: "354",
        currency: "ISK",
    },
    {
        name: "Italy",
        countryCode: "IT",
        phone: "39",
        currency: "EUR",
    },
    {
        name: "Jersey",
        countryCode: "JE",
        phone: "+44-1534",
        currency: "GBP",
    },
    {
        name: "Jamaica",
        countryCode: "JM",
        phone: "+1-876",
        currency: "JMD",
    },
    {
        name: "Jordan",
        countryCode: "JO",
        phone: "962",
        currency: "JOD",
    },
    {
        name: "Japan",
        countryCode: "JP",
        phone: "81",
        currency: "JPY",
    },
    {
        name: "Kenya",
        countryCode: "KE",
        phone: "254",
        currency: "KES",
    },
    {
        name: "Kyrgyzstan",
        countryCode: "KG",
        phone: "996",
        currency: "KGS",
    },
    {
        name: "Cambodia",
        countryCode: "KH",
        phone: "855",
        currency: "KHR",
    },
    {
        name: "Kiribati",
        countryCode: "KI",
        phone: "686",
        currency: "AUD",
    },
    {
        name: "Comoros",
        countryCode: "KM",
        phone: "269",
        currency: "KMF",
    },
    {
        name: "Saint Kitts and Nevis",
        countryCode: "KN",
        phone: "+1-869",
        currency: "XCD",
    },
    {
        name: "North Korea",
        countryCode: "KP",
        phone: "850",
        currency: "KPW",
    },
    {
        name: "South Korea",
        countryCode: "KR",
        phone: "82",
        currency: "KRW",
    },
    {
        name: "Kosovo",
        countryCode: "XK",
        phone: "",
        currency: "EUR",
    },
    {
        name: "Kuwait",
        countryCode: "KW",
        phone: "965",
        currency: "KWD",
    },
    {
        name: "Cayman Islands",
        countryCode: "KY",
        phone: "+1-345",
        currency: "KYD",
    },
    {
        name: "Kazakhstan",
        countryCode: "KZ",
        phone: "7",
        currency: "KZT",
    },
    {
        name: "Laos",
        countryCode: "LA",
        phone: "856",
        currency: "LAK",
    },
    {
        name: "Lebanon",
        countryCode: "LB",
        phone: "961",
        currency: "LBP",
    },
    {
        name: "Saint Lucia",
        countryCode: "LC",
        phone: "+1-758",
        currency: "XCD",
    },
    {
        name: "Liechtenstein",
        countryCode: "LI",
        phone: "423",
        currency: "CHF",
    },
    {
        name: "Sri Lanka",
        countryCode: "LK",
        phone: "94",
        currency: "LKR",
    },
    {
        name: "Liberia",
        countryCode: "LR",
        phone: "231",
        currency: "LRD",
    },
    {
        name: "Lesotho",
        countryCode: "LS",
        phone: "266",
        currency: "LSL",
    },
    {
        name: "Lithuania",
        countryCode: "LT",
        phone: "370",
        currency: "EUR",
    },
    {
        name: "Luxembourg",
        countryCode: "LU",
        phone: "352",
        currency: "EUR",
    },
    {
        name: "Latvia",
        countryCode: "LV",
        phone: "371",
        currency: "EUR",
    },
    {
        name: "Libya",
        countryCode: "LY",
        phone: "218",
        currency: "LYD",
    },
    {
        name: "Morocco",
        countryCode: "MA",
        phone: "212",
        currency: "MAD",
    },
    {
        name: "Monaco",
        countryCode: "MC",
        phone: "377",
        currency: "EUR",
    },
    {
        name: "Moldova",
        countryCode: "MD",
        phone: "373",
        currency: "MDL",
    },
    {
        name: "Montenegro",
        countryCode: "ME",
        phone: "382",
        currency: "EUR",
    },
    {
        name: "Saint Martin",
        countryCode: "MF",
        phone: "590",
        currency: "EUR",
    },
    {
        name: "Madagascar",
        countryCode: "MG",
        phone: "261",
        currency: "MGA",
    },
    {
        name: "Marshall Islands",
        countryCode: "MH",
        phone: "692",
        currency: "USD",
    },
    {
        name: "North Macedonia",
        countryCode: "MK",
        phone: "389",
        currency: "MKD",
    },
    {
        name: "Mali",
        countryCode: "ML",
        phone: "223",
        currency: "XOF",
    },
    {
        name: "Myanmar",
        countryCode: "MM",
        phone: "95",
        currency: "MMK",
    },
    {
        name: "Mongolia",
        countryCode: "MN",
        phone: "976",
        currency: "MNT",
    },
    {
        name: "Macao",
        countryCode: "MO",
        phone: "853",
        currency: "MOP",
    },
    {
        name: "Northern Mariana Islands",
        countryCode: "MP",
        phone: "+1-670",
        currency: "USD",
    },
    {
        name: "Martinique",
        countryCode: "MQ",
        phone: "596",
        currency: "EUR",
    },
    {
        name: "Mauritania",
        countryCode: "MR",
        phone: "222",
        currency: "MRU",
    },
    {
        name: "Montserrat",
        countryCode: "MS",
        phone: "+1-664",
        currency: "XCD",
    },
    {
        name: "Malta",
        countryCode: "MT",
        phone: "356",
        currency: "EUR",
    },
    {
        name: "Mauritius",
        countryCode: "MU",
        phone: "230",
        currency: "MUR",
    },
    {
        name: "Maldives",
        countryCode: "MV",
        phone: "960",
        currency: "MVR",
    },
    {
        name: "Malawi",
        countryCode: "MW",
        phone: "265",
        currency: "MWK",
    },
    {
        name: "Mexico",
        countryCode: "MX",
        phone: "52",
        currency: "MXN",
    },
    {
        name: "Malaysia",
        countryCode: "MY",
        phone: "60",
        currency: "MYR",
    },
    {
        name: "Mozambique",
        countryCode: "MZ",
        phone: "258",
        currency: "MZN",
    },
    {
        name: "Namibia",
        countryCode: "NA",
        phone: "264",
        currency: "NAD",
    },
    {
        name: "New Caledonia",
        countryCode: "NC",
        phone: "687",
        currency: "XPF",
    },
    {
        name: "Niger",
        countryCode: "NE",
        phone: "227",
        currency: "XOF",
    },
    {
        name: "Norfolk Island",
        countryCode: "NF",
        phone: "672",
        currency: "AUD",
    },
    {
        name: "Nigeria",
        countryCode: "NG",
        phone: "234",
        currency: "NGN",
    },
    {
        name: "Nicaragua",
        countryCode: "NI",
        phone: "505",
        currency: "NIO",
    },
    {
        name: "The Netherlands",
        countryCode: "NL",
        phone: "31",
        currency: "EUR",
    },
    {
        name: "Norway",
        countryCode: "NO",
        phone: "47",
        currency: "NOK",
    },
    {
        name: "Nepal",
        countryCode: "NP",
        phone: "977",
        currency: "NPR",
    },
    {
        name: "Nauru",
        countryCode: "NR",
        phone: "674",
        currency: "AUD",
    },
    {
        name: "Niue",
        countryCode: "NU",
        phone: "683",
        currency: "NZD",
    },
    {
        name: "New Zealand",
        countryCode: "NZ",
        phone: "64",
        currency: "NZD",
    },
    {
        name: "Oman",
        countryCode: "OM",
        phone: "968",
        currency: "OMR",
    },
    {
        name: "Panama",
        countryCode: "PA",
        phone: "507",
        currency: "PAB",
    },
    {
        name: "Peru",
        countryCode: "PE",
        phone: "51",
        currency: "PEN",
    },
    {
        name: "French Polynesia",
        countryCode: "PF",
        phone: "689",
        currency: "XPF",
    },
    {
        name: "Papua New Guinea",
        countryCode: "PG",
        phone: "675",
        currency: "PGK",
    },
    {
        name: "Philippines",
        countryCode: "PH",
        phone: "63",
        currency: "PHP",
    },
    {
        name: "Pakistan",
        countryCode: "PK",
        phone: "92",
        currency: "PKR",
    },
    {
        name: "Poland",
        countryCode: "PL",
        phone: "48",
        currency: "PLN",
    },
    {
        name: "Saint Pierre and Miquelon",
        countryCode: "PM",
        phone: "508",
        currency: "EUR",
    },
    {
        name: "Pitcairn",
        countryCode: "PN",
        phone: "870",
        currency: "NZD",
    },
    {
        name: "Puerto Rico",
        countryCode: "PR",
        phone: "+1-787 and 1-939",
        currency: "USD",
    },
    {
        name: "Palestinian Territory",
        countryCode: "PS",
        phone: "970",
        currency: "ILS",
    },
    {
        name: "Portugal",
        countryCode: "PT",
        phone: "351",
        currency: "EUR",
    },
    {
        name: "Palau",
        countryCode: "PW",
        phone: "680",
        currency: "USD",
    },
    {
        name: "Paraguay",
        countryCode: "PY",
        phone: "595",
        currency: "PYG",
    },
    {
        name: "Qatar",
        countryCode: "QA",
        phone: "974",
        currency: "QAR",
    },
    {
        name: "Reunion",
        countryCode: "RE",
        phone: "262",
        currency: "EUR",
    },
    {
        name: "Romania",
        countryCode: "RO",
        phone: "40",
        currency: "RON",
    },
    {
        name: "Serbia",
        countryCode: "RS",
        phone: "381",
        currency: "RSD",
    },
    {
        name: "Russia",
        countryCode: "RU",
        phone: "7",
        currency: "RUB",
    },
    {
        name: "Rwanda",
        countryCode: "RW",
        phone: "250",
        currency: "RWF",
    },
    {
        name: "Saudi Arabia",
        countryCode: "SA",
        phone: "966",
        currency: "SAR",
    },
    {
        name: "Solomon Islands",
        countryCode: "SB",
        phone: "677",
        currency: "SBD",
    },
    {
        name: "Seychelles",
        countryCode: "SC",
        phone: "248",
        currency: "SCR",
    },
    {
        name: "Sudan",
        countryCode: "SD",
        phone: "249",
        currency: "SDG",
    },
    {
        name: "South Sudan",
        countryCode: "SS",
        phone: "211",
        currency: "SSP",
    },
    {
        name: "Sweden",
        countryCode: "SE",
        phone: "46",
        currency: "SEK",
    },
    {
        name: "Singapore",
        countryCode: "SG",
        phone: "65",
        currency: "SGD",
    },
    {
        name: "Saint Helena",
        countryCode: "SH",
        phone: "290",
        currency: "SHP",
    },
    {
        name: "Slovenia",
        countryCode: "SI",
        phone: "386",
        currency: "EUR",
    },
    {
        name: "Svalbard and Jan Mayen",
        countryCode: "SJ",
        phone: "47",
        currency: "NOK",
    },
    {
        name: "Slovakia",
        countryCode: "SK",
        phone: "421",
        currency: "EUR",
    },
    {
        name: "Sierra Leone",
        countryCode: "SL",
        phone: "232",
        currency: "SLL",
    },
    {
        name: "San Marino",
        countryCode: "SM",
        phone: "378",
        currency: "EUR",
    },
    {
        name: "Senegal",
        countryCode: "SN",
        phone: "221",
        currency: "XOF",
    },
    {
        name: "Somalia",
        countryCode: "SO",
        phone: "252",
        currency: "SOS",
    },
    {
        name: "Suriname",
        countryCode: "SR",
        phone: "597",
        currency: "SRD",
    },
    {
        name: "Sao Tome and Principe",
        countryCode: "ST",
        phone: "239",
        currency: "STN",
    },
    {
        name: "El Salvador",
        countryCode: "SV",
        phone: "503",
        currency: "USD",
    },
    {
        name: "Sint Maarten",
        countryCode: "SX",
        phone: "599",
        currency: "ANG",
    },
    {
        name: "Syria",
        countryCode: "SY",
        phone: "963",
        currency: "SYP",
    },
    {
        name: "Eswatini",
        countryCode: "SZ",
        phone: "268",
        currency: "SZL",
    },
    {
        name: "Turks and Caicos Islands",
        countryCode: "TC",
        phone: "+1-649",
        currency: "USD",
    },
    {
        name: "Chad",
        countryCode: "TD",
        phone: "235",
        currency: "XAF",
    },
    {
        name: "French Southern Territories",
        countryCode: "TF",
        phone: "",
        currency: "EUR",
    },
    {
        name: "Togo",
        countryCode: "TG",
        phone: "228",
        currency: "XOF",
    },
    {
        name: "Thailand",
        countryCode: "TH",
        phone: "66",
        currency: "THB",
    },
    {
        name: "Tajikistan",
        countryCode: "TJ",
        phone: "992",
        currency: "TJS",
    },
    {
        name: "Tokelau",
        countryCode: "TK",
        phone: "690",
        currency: "NZD",
    },
    {
        name: "Timor Leste",
        countryCode: "TL",
        phone: "670",
        currency: "USD",
    },
    {
        name: "Turkmenistan",
        countryCode: "TM",
        phone: "993",
        currency: "TMT",
    },
    {
        name: "Tunisia",
        countryCode: "TN",
        phone: "216",
        currency: "TND",
    },
    {
        name: "Tonga",
        countryCode: "TO",
        phone: "676",
        currency: "TOP",
    },
    {
        name: "Turkey",
        countryCode: "TR",
        phone: "90",
        currency: "TRY",
    },
    {
        name: "Trinidad and Tobago",
        countryCode: "TT",
        phone: "+1-868",
        currency: "TTD",
    },
    {
        name: "Tuvalu",
        countryCode: "TV",
        phone: "688",
        currency: "AUD",
    },
    {
        name: "Taiwan",
        countryCode: "TW",
        phone: "886",
        currency: "TWD",
    },
    {
        name: "Tanzania",
        countryCode: "TZ",
        phone: "255",
        currency: "TZS",
    },
    {
        name: "Ukraine",
        countryCode: "UA",
        phone: "380",
        currency: "UAH",
    },
    {
        name: "Uganda",
        countryCode: "UG",
        phone: "256",
        currency: "UGX",
    },
    {
        name: "United States Minor Outlying Islands",
        countryCode: "UM",
        phone: "1",
        currency: "USD",
    },
    {
        name: "United States",
        countryCode: "US",
        phone: "1",
        currency: "USD",
    },
    {
        name: "Uruguay",
        countryCode: "UY",
        phone: "598",
        currency: "UYU",
    },
    {
        name: "Uzbekistan",
        countryCode: "UZ",
        phone: "998",
        currency: "UZS",
    },
    {
        name: "Vatican",
        countryCode: "VA",
        phone: "379",
        currency: "EUR",
    },
    {
        name: "Saint Vincent and the Grenadines",
        countryCode: "VC",
        phone: "+1-784",
        currency: "XCD",
    },
    {
        name: "Venezuela",
        countryCode: "VE",
        phone: "58",
        currency: "VES",
    },
    {
        name: "British Virgin Islands",
        countryCode: "VG",
        phone: "+1-284",
        currency: "USD",
    },
    {
        name: "U.S. Virgin Islands",
        countryCode: "VI",
        phone: "+1-340",
        currency: "USD",
    },
    {
        name: "Vietnam",
        countryCode: "VN",
        phone: "84",
        currency: "VND",
    },
    {
        name: "Vanuatu",
        countryCode: "VU",
        phone: "678",
        currency: "VUV",
    },
    {
        name: "Wallis and Futuna",
        countryCode: "WF",
        phone: "681",
        currency: "XPF",
    },
    {
        name: "Samoa",
        countryCode: "WS",
        phone: "685",
        currency: "WST",
    },
    {
        name: "Yemen",
        countryCode: "YE",
        phone: "967",
        currency: "YER",
    },
    {
        name: "Mayotte",
        countryCode: "YT",
        phone: "262",
        currency: "EUR",
    },
    {
        name: "South Africa",
        countryCode: "ZA",
        phone: "27",
        currency: "ZAR",
    },
    {
        name: "Zambia",
        countryCode: "ZM",
        phone: "260",
        currency: "ZMW",
    },
    {
        name: "Zimbabwe",
        countryCode: "ZW",
        phone: "263",
        currency: "ZWL",
    },
    {
        name: "Serbia and Montenegro",
        countryCode: "CS",
        phone: "381",
        currency: "RSD",
    },
    {
        name: "Netherlands Antilles",
        countryCode: "AN",
        phone: "599",
        currency: "ANG",
    },
];
