export const GLOBAL_TEXT = {
    create_your_profile: "Create your Profile",
    school: "School",
    student: "Student",
    create_account: "Continue to create account",
    login_to_continue: "Please enter your details to sign in",
    tell_about_yourself: "Tell us about yourself",
    enter_mobile_number: "Enter your mobile number",
    enter_email_id: "Enter your email",
    validate_mobile: "Please provide valid mobile number",
    validate_email: "Please provide valid email",
    enter_pin: "Enter Your OTP",
    continue_n_verify: "Continue & verify",
    additional_details: "Additional Details",
    find_your_destination: "Find your destination",
    popular_schools: "Popular Schools",
    popular_courses: "Popular Courses",
    choose_your_language: "Choose your language to learn",
    inrease_your_chance: "Increase your Chances",
    explore_more: "Explore More",
    latest_events: "Latest Events",
    facilities: "Facilities",
    contact_now: "Contact Now",
    ratings_and_review: "Ratings and review",
    contact_details: "Contact Details",
    enquire_now: "Enquire Now",
    My_Favorite_Courses: "Courses",
    My_Favorite_Schools: "Schools",
    My_Favorite_Cities: "Countries",
    course_details: "Course Details",
    select_your_plan: "Select your plan",
    book_your_seat: "Book your seat",
    buy_now: "Buy Now",
    similar_courses: "Similar Courses",
    welcome_to_my_school: "Welcome to my school",
    ongoing_courses: "Ongoing Courses",
    recent_courses: "Recently Added",
    upcoming_courses: "Upcoming Courses",
    logout: "Logout",
    singup: "Sign Up",
    login: "Login",
    plan_one: "Plan 1",
    plan_two: "Plan 2",
    plan_three: "Plan 3",
    overview: "Overview",
    courses: "Courses",
    photo_gallery: "Photo Gallery",
    your_selected_plan: "Your selected plan is",
    select_payment_mode: "Select Payment Mode",
    confirm_your_payment: "Confirm your payment",
    my_added_courses_in_cart: "My added courses in cart",
    your_cart_is_empty: "Your cart is empty",
};
export const GLOBAL_TRANSLATION_LABEL = {
    find_your_destination: "find_your_destination",
    popular_school: "popular_school",
    choose_your_language_to_learn: "choose_your_language_to_learn",
    popular_Courses: "popular_courses",
    starting_from: "starting_from",
    view_all: "view_all",
    increase_your_chances: "increase_your_chances",
    home: "home",
    favourite: "favourite",
    compare: "compare",
    cart: "cart",
    account: "Account",
    courses: "courses",
    welcome_back: "welcome_back",
    termsPolicy: "termsPolicy",
    darkMode: "darkMode",
    lightMode: "lightMode",
    logout: "logout",
    hii: "hii",
    overview: "overview",
    contactNow: "contactNow",
    enquireNow: "enquireNow",
    ratingsAndReview: "ratingsAndReview",
    selectYourPlan: "selectYourPlan",
    courseDetails: "courseDetails",
    courseFees: "courseFees",
    totalFee: "totalFee",
    bookYourSeat: "bookYourSeat",
    rating: "rating",
    similarCourses: "similarCourses",
    yourSelectedPlanIs: "yourSelectedPlanIs",
    duration: "duration",
    fee: "fee",
    taxes: "taxes",
    total: "total",
    selectPaymentMode: "selectPaymentMode",
    hyperPay: "hyperPay",
    cardPayment: "cardPayment",
    netBanking: "netBanking",
    confirmYourPayment: "confirmYourPayment",
    facilities: "facilities",
    latestEvents: "latestEvents",
};
export const SIGNUP_FIELDS = {
    name: { label: "Name", placeholder: "e.g John Doe", type: "INPUT" },
    email: {
        label: "Email",
        placeholder: "e.g john.doe@gmail.com",
        type: "INPUT",
    },
    phone: {
        label: "Mobile Number",
        placeholder: "Enter your phone number",
        type: "INPUT",
    },
};

export const ENQUIRY_FIELDS = {
    name: {
        label: "Enter your name",
        placeholder: "e.g John Doe",
        type: "INPUT",
    },
    nationality: {
        label: "Nationality",
        placeholder: "Please specify",
        type: "DROPDOWN",
    },
    phone: {
        label: "Phone Number",
        placeholder: "Enter your number",
        type: "INPUT",
    },
    email: {
        label: "Mail ID",
        placeholder: "e.g john.doe@gmail.com",
        type: "INPUT",
    },
    date: {
        label: "When you want to start course?",
        placeholder: "DD/MM/YY",
        type: "INPUT",
    },
    language: {
        label: "Select Language to learn",
        placeholder: "Please specify",
        type: "DROPDOWN",
    },
    accommodation: {
        label: "Select your accommodation",
        placeholder: "Please specify",
        type: "DROPDOWN",
    },
    comment: {
        label: "Add comment",
        placeholder: "Enter your message",
        type: "INPUT",
    },
};

export const DETAILS_FIELDS = {
    qualification: {
        label: "My Qualification",
        type: "DROPDOWN",
        placeholder: "Select qualification",
    },
    academic: {
        label: "Academic Session",
        type: "DROPDOWN",
        placeholder: "Select academic",
    },
    language: {
        label: "Select Language",
        type: "DROPDOWN",
        placeholder: "Select language",
    },
    country: {
        label: "Looking for country",
        type: "DROPDOWN",
        placeholder: "Select country",
    },
    state: {
        label: "State",
        type: "DROPDOWN",
        placeholder: "Select state",
    },
    city: {
        label: "City",
        type: "DROPDOWN",
        placeholder: "Select city",
    },
};
