export const API_URL = {
    hello: "hello",
    sendOTP: "auth/send-otp",
    verifyOTP: "auth/verify-otp",
    register: "auth/register",
    login: "auth/login",
    resendOTP: "auth/resend-otp",
    school: "school",
    course: "course",
    schoolOverview: "school/schoolOverview",
    enquiry: "enquiry",
    favorite: "favorite",
    user: "user",
    country: "country",
    cart: "cart",
    plan: "plan",
    purchaseCourse: "course/purchaseCourse",
    schoolComparison: "school/schoolComparison",
};
