export const countriesData = [
    {
        name: "United States of America",
        code: "US",
        language: {
            code: "en",
            iso639_2: "eng",
            name: "English",
            nativeName: "English",
        },
        dialling_code: "+1",
        isoCode: "840",
        uniqueId: "united_states_of_america_548352",
        flag: "https://flagcdn.com/w320/us.png",
    },
    {
        name: "United Kingdom of Great Britain and Northern Ireland",
        code: "GB",
        language: {
            code: "en",
            name: "English(UK)",
        },
        dialling_code: "+44",
        isoCode: "826",
        uniqueId: "united_kingdom_of_great_britain_and_northern_ireland_785299",
        flag: "https://flagcdn.com/w320/gb.png",
    },
    {
        name: "Saudi Arabia",
        code: "SA",
        language: {
            code: "ar",
            name: "Arabic",
        },
        dialling_code: "+966",
        isoCode: "682",
        uniqueId: "saudi_arabia_944587",
        flag: "https://flagcdn.com/w320/sa.png",
    },
    {
        name: "Iran (Islamic Republic of)",
        code: "IR",
        language: {
            code: "fa",
            name: "Farsi",
        },
        dialling_code: "+98",
        isoCode: "364",
        uniqueId: "iran_(islamic_republic_of)_229980",
        flag: "https://flagcdn.com/w320/ir.png",
    },
    {
        name: "Turkey",
        code: "TR",
        language: {
            code: "tr",
            name: "Turkish",
        },
        dialling_code: "+90",
        isoCode: "792",
        uniqueId: "turkey_706610",
        flag: "https://flagcdn.com/w320/tr.png",
    },
    {
        name: "Afghanistan",
        code: "AF",
        language: {
            code: "ps",
            name: "Pashto",
        },
        dialling_code: "+93",
        isoCode: "004",
        uniqueId: "afghanistan_35779",
        flag: "https://flagcdn.com/w320/af.png",
    },
    {
        name: "Albania",
        code: "AL",
        language: {
            code: "sq",
            name: "Albanian",
        },
        dialling_code: "+355",
        isoCode: "008",
        uniqueId: "albania_339069",
        flag: "https://flagcdn.com/w320/al.png",
    },
    {
        name: "Algeria",
        code: "DZ",
        language: {
            code: "ar",
            name: "Arabic",
        },
        dialling_code: "+213",
        isoCode: "012",
        uniqueId: "algeria_926734",
        flag: "https://flagcdn.com/w320/dz.png",
    },
    {
        name: "American Samoa",
        code: "AS",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+1",
        isoCode: "016",
        uniqueId: "american_samoa_685391",
        flag: "https://flagcdn.com/w320/as.png",
    },
    {
        name: "Andorra",
        code: "AD",
        language: {
            code: "ca",
            name: "Catalan",
        },
        dialling_code: "+376",
        isoCode: "020",
        uniqueId: "andorra_235109",
        flag: "https://flagcdn.com/w320/ad.png",
    },
    {
        name: "Angola",
        code: "AO",
        language: {
            code: "pt",
            name: "Portuguese",
        },
        dialling_code: "+244",
        isoCode: "024",
        uniqueId: "angola_289902",
        flag: "https://flagcdn.com/w320/ao.png",
    },
    {
        name: "Anguilla",
        code: "AI",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+43",
        isoCode: "660",
        uniqueId: "anguilla_474918",
        flag: "https://flagcdn.com/w320/ai.png",
    },
    {
        name: "Antigua and Barbuda",
        code: "AG",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+1",
        isoCode: "028",
        uniqueId: "antigua_and_barbuda_406088",
        flag: "https://flagcdn.com/w320/ag.png",
    },
    {
        name: "Argentina",
        code: "AR",
        language: {
            code: "es",
            name: "Spanish",
        },
        dialling_code: "+54",
        isoCode: "032",
        uniqueId: "argentina_509654",
        flag: "https://flagcdn.com/w320/ar.png",
    },
    {
        name: "Armenia",
        code: "AM",
        language: {
            code: "hy",
            name: "Armenian",
        },
        dialling_code: "+374",
        isoCode: "051",
        uniqueId: "armenia_379990",
        flag: "https://flagcdn.com/w320/am.png",
    },
    {
        name: "Aruba",
        code: "AW",
        language: {
            code: "nl",
            name: "Dutch",
        },
        dialling_code: "+297",
        isoCode: "533",
        uniqueId: "aruba_275550",
        flag: "https://flagcdn.com/w320/aw.png",
    },
    {
        name: "Australia",
        code: "AU",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+61",
        isoCode: "036",
        uniqueId: "australia_708459",
        flag: "https://flagcdn.com/w320/au.png",
    },
    {
        name: "Azerbaijan",
        code: "AZ",
        language: {
            code: "az",
            name: "Azerbaijani",
        },
        dialling_code: "+994",
        isoCode: "031",
        uniqueId: "azerbaijan_224911",
        flag: "https://flagcdn.com/w320/az.png",
    },
    {
        name: "Bahamas",
        code: "BS",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+1",
        isoCode: "044",
        uniqueId: "bahamas_965186",
        flag: "https://flagcdn.com/w320/bs.png",
    },
    {
        name: "Bahrain",
        code: "BH",
        language: {
            code: "ar",
            name: "Arabic",
        },
        dialling_code: "+973",
        isoCode: "048",
        uniqueId: "bahrain_516600",
        flag: "https://flagcdn.com/w320/bh.png",
    },
    {
        name: "Bangladesh",
        code: "BD",
        language: {
            code: "bn",
            name: "Bengali",
        },
        dialling_code: "+880",
        isoCode: "050",
        uniqueId: "bangladesh_754600",
        flag: "https://flagcdn.com/w320/bd.png",
    },
    {
        name: "Barbados",
        code: "BB",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+1",
        isoCode: "052",
        uniqueId: "barbados_30199",
        flag: "https://flagcdn.com/w320/bb.png",
    },
    {
        name: "Belarus",
        code: "BY",
        language: {
            code: "be",
            name: "Belarusian",
        },
        dialling_code: "+375",
        isoCode: "112",
        uniqueId: "belarus_944850",
        flag: "https://flagcdn.com/w320/by.png",
    },
    {
        name: "Belgium",
        code: "BE",
        language: {
            code: "nl",
            name: "Dutch",
        },
        dialling_code: "+32",
        isoCode: "056",
        uniqueId: "belgium_621180",
        flag: "https://flagcdn.com/w320/be.png",
    },
    {
        name: "Belize",
        code: "BZ",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+501",
        isoCode: "084",
        uniqueId: "belize_191065",
        flag: "https://flagcdn.com/w320/bz.png",
    },
    {
        name: "Benin",
        code: "BJ",
        language: {
            code: "fr",
            name: "French",
        },
        dialling_code: "+229",
        isoCode: "204",
        uniqueId: "benin_280690",
        flag: "https://flagcdn.com/w320/bj.png",
    },
    {
        name: "Bermuda",
        code: "BM",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+1",
        isoCode: "060",
        uniqueId: "bermuda_425091",
        flag: "https://flagcdn.com/w320/bm.png",
    },
    {
        name: "Bhutan",
        code: "BT",
        language: {
            code: "dz",
            name: "Dzongkha",
        },
        dialling_code: "+975",
        isoCode: "064",
        uniqueId: "bhutan_84314",
        flag: "https://flagcdn.com/w320/bt.png",
    },
    {
        name: "Bolivia (Plurinational State of)",
        code: "BO",
        language: {
            code: "es",
            name: "Spanish",
        },
        dialling_code: "+591",
        isoCode: "068",
        uniqueId: "bolivia_(plurinational_state_of)_153440",
        flag: "https://flagcdn.com/w320/bo.png",
    },
    {
        name: "Bosnia and Herzegovina",
        code: "BA",
        language: {
            code: "bs",
            name: "Bosnian",
        },
        dialling_code: "+387",
        isoCode: "070",
        uniqueId: "bosnia_and_herzegovina_595614",
        flag: "https://flagcdn.com/w320/ba.png",
    },
    {
        name: "Botswana",
        code: "BW",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+267",
        isoCode: "072",
        uniqueId: "botswana_1931",
        flag: "https://flagcdn.com/w320/bw.png",
    },
    {
        name: "Brazil",
        code: "BR",
        language: {
            code: "pt",
            name: "Portuguese",
        },
        dialling_code: "+55",
        isoCode: "076",
        uniqueId: "brazil_751798",
        flag: "https://flagcdn.com/w320/br.png",
    },
    {
        name: "British Indian Ocean Territory",
        code: "IO",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+246",
        isoCode: "086",
        uniqueId: "british_indian_ocean_territory_575684",
        flag: "https://flagcdn.com/w320/io.png",
    },
    {
        name: "Virgin Islands (British)",
        code: "VG",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+1",
        isoCode: "092",
        uniqueId: "virgin_islands_(british)_526323",
        flag: "https://flagcdn.com/w320/vg.png",
    },
    {
        name: "Virgin Islands (U.S.)",
        code: "VI",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+1",
        isoCode: "850",
        uniqueId: "virgin_islands_(u.s.)_367225",
        flag: "https://flagcdn.com/w320/vi.png",
    },
    {
        name: "Brunei Darussalam",
        code: "BN",
        language: {
            code: "ms",
            name: "Malay",
        },
        dialling_code: "+673",
        isoCode: "096",
        uniqueId: "brunei_darussalam_351536",
        flag: "https://flagcdn.com/w320/bn.png",
    },
    {
        name: "Bulgaria",
        code: "BG",
        language: {
            code: "bg",
            name: "Bulgarian",
        },
        dialling_code: "+359",
        isoCode: "100",
        uniqueId: "bulgaria_488242",
        flag: "https://flagcdn.com/w320/bg.png",
    },
    {
        name: "Burkina Faso",
        code: "BF",
        language: {
            code: "fr",
            name: "French",
        },
        dialling_code: "+226",
        isoCode: "854",
        uniqueId: "burkina_faso_392878",
        flag: "https://flagcdn.com/w320/bf.png",
    },
    {
        name: "Burundi",
        code: "BI",
        language: {
            code: "fr",
            name: "French",
        },
        dialling_code: "+257",
        isoCode: "108",
        uniqueId: "burundi_256027",
        flag: "https://flagcdn.com/w320/bi.png",
    },
    {
        name: "Cambodia",
        code: "KH",
        language: {
            code: "km",
            name: "Khmer",
        },
        dialling_code: "+855",
        isoCode: "116",
        uniqueId: "cambodia_258787",
        flag: "https://flagcdn.com/w320/kh.png",
    },
    {
        name: "Cameroon",
        code: "CM",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+237",
        isoCode: "120",
        uniqueId: "cameroon_867995",
        flag: "https://flagcdn.com/w320/cm.png",
    },
    {
        name: "Canada",
        code: "CA",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+1",
        isoCode: "124",
        uniqueId: "canada_993603",
        flag: "https://flagcdn.com/w320/ca.png",
    },
    {
        name: "Cabo Verde",
        code: "CV",
        language: {
            code: "pt",
            iso639_2: "por",
            name: "Portuguese",
            nativeName: "Português",
        },
        dialling_code: "+238",
        isoCode: "132",
        uniqueId: "cabo_verde_960329",
        flag: "https://flagcdn.com/w320/cv.png",
    },
    {
        name: "Cayman Islands",
        code: "KY",
        demonym: "Caymanian",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+1",
        isoCode: "136",
        uniqueId: "cayman_islands_312454",
        flag: "https://flagcdn.com/w320/ky.png",
    },
    {
        name: "Central African Republic",
        code: "CF",
        language: {
            code: "fr",
            name: "French",
        },
        dialling_code: "+236",
        isoCode: "140",
        uniqueId: "central_african_republic_729129",
        flag: "https://flagcdn.com/w320/cf.png",
    },
    {
        name: "Central African Republic",
        code: "CF",
        language: {
            code: "fr",
            name: "French",
        },
        dialling_code: "+236",
        isoCode: "140",
        uniqueId: "central_african_republic_945384",
        flag: "https://flagcdn.com/w320/cf.png",
    },
    {
        name: "Chile",
        code: "CL",
        language: {
            code: "es",
            iso639_2: "spa",
            name: "Spanish",
            nativeName: "Español",
        },
        dialling_code: "+56",
        isoCode: "152",
        uniqueId: "chile_653245",
        flag: "https://flagcdn.com/w320/cl.png",
    },
    {
        name: "China",
        code: "CN",
        language: {
            code: "zh",
            name: "Chinese",
        },
        dialling_code: "+86",
        isoCode: "156",
        uniqueId: "china_93074",
        flag: "https://flagcdn.com/w320/cn.png",
    },
    {
        name: "Colombia",
        code: "CO",
        language: {
            code: "es",
            name: "Spanish",
        },
        dialling_code: "+57",
        isoCode: "170",
        uniqueId: "colombia_806813",
        flag: "https://flagcdn.com/w320/co.png",
    },
    {
        name: "Comoros",
        code: "KM",
        language: {
            code: "fr",
            name: "French",
        },
        dialling_code: "+269",
        isoCode: "174",
        uniqueId: "comoros_629062",
        flag: "https://flagcdn.com/w320/km.png",
    },
    {
        name: "Congo",
        code: "CG",
        language: {
            code: "fr",
            name: "French",
        },
        dialling_code: "+242",
        isoCode: "178",
        uniqueId: "congo_772287",
        flag: "https://flagcdn.com/w320/cg.png",
    },
    {
        name: "Congo (Democratic Republic of the)",
        code: "CD",
        language: {
            code: "fr",
            name: "French",
        },
        dialling_code: "+243",
        isoCode: "180",
        uniqueId: "congo_(democratic_republic_of_the)_744464",
        flag: "https://flagcdn.com/w320/cd.png",
    },
    {
        name: "Cook Islands",
        code: "CK",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+682",
        isoCode: "184",
        uniqueId: "cook_islands_129953",
        flag: "https://flagcdn.com/w320/ck.png",
    },
    {
        name: "Costa Rica",
        code: "CR",
        language: {
            code: "es",
            name: "Spanish",
        },
        dialling_code: "+506",
        isoCode: "188",
        uniqueId: "costa_rica_290773",
        flag: "https://flagcdn.com/w320/cr.png",
    },
    {
        name: "Croatia",
        code: "HR",
        language: {
            code: "hr",
            name: "Croatian",
        },
        dialling_code: "+385",
        isoCode: "191",
        uniqueId: "croatia_990",
        flag: "https://flagcdn.com/w320/hr.png",
    },
    {
        name: "Cuba",
        code: "CU",
        language: {
            code: "es",
            name: "Spanish",
        },
        dialling_code: "+53",
        isoCode: "192",
        uniqueId: "cuba_39840",
        flag: "https://flagcdn.com/w320/cu.png",
    },
    {
        name: "Cuba",
        code: "CU",
        language: {
            code: "es",
            name: "Spanish",
        },
        dialling_code: "+53",
        isoCode: "192",
        uniqueId: "cuba_45460",
        flag: "https://flagcdn.com/w320/cu.png",
    },
    {
        name: "Cyprus",
        code: "CY",
        language: {
            code: "tr",
            name: "Turkish",
        },
        dialling_code: "+357",
        isoCode: "196",
        uniqueId: "cyprus_950385",
        flag: "https://flagcdn.com/w320/cy.png",
    },
    {
        name: "Czech Republic",
        code: "CZ",
        language: {
            code: "cs",
            name: "Czech",
        },
        dialling_code: "+420",
        isoCode: "203",
        uniqueId: "czech_republic_740420",
        flag: "https://flagcdn.com/w320/cz.png",
    },
    {
        name: "Denmark",
        code: "DK",
        language: {
            code: "da",
            name: "Danish",
        },
        dialling_code: "+45",
        isoCode: "208",
        uniqueId: "denmark_718583",
        flag: "https://flagcdn.com/w320/dk.png",
    },
    {
        name: "Djibouti",
        code: "DJ",
        language: {
            code: "fr",
            name: "French",
        },
        dialling_code: "+253",
        isoCode: "262",
        uniqueId: "djibouti_11297",
        flag: "https://flagcdn.com/w320/dj.png",
    },
    {
        name: "Dominica",
        code: "DM",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+1",
        isoCode: "212",
        uniqueId: "dominica_347584",
        flag: "https://flagcdn.com/w320/dm.png",
    },
    {
        name: "Dominican Republic",
        code: "DO",
        language: {
            code: "es",
            name: "Spanish",
        },
        dialling_code: "+1",
        isoCode: "214",
        uniqueId: "dominican_republic_514604",
        flag: "https://flagcdn.com/w320/do.png",
    },
    {
        name: "Ecuador",
        code: "EC",
        language: {
            code: "es",
            name: "Spanish",
        },
        dialling_code: "+593",
        isoCode: "218",
        uniqueId: "ecuador_69154",
        flag: "https://flagcdn.com/w320/ec.png",
    },
    {
        name: "Egypt",
        code: "EG",
        language: {
            code: "ar",
            name: "Arabic",
        },
        dialling_code: "+20",
        isoCode: "818",
        uniqueId: "egypt_727886",
        flag: "https://flagcdn.com/w320/eg.png",
    },
    {
        name: "El Salvador",
        code: "SV",
        language: {
            code: "es",
            name: "Spanish",
        },
        dialling_code: "+503",
        isoCode: "222",
        uniqueId: "el_salvador_88260",
        flag: "https://flagcdn.com/w320/sv.png",
    },
    {
        name: "Equatorial Guinea",
        code: "GQ",
        language: {
            code: "es",
            iso639_2: "spa",
            name: "Spanish",
            nativeName: "Español",
        },
        dialling_code: "+240",
        isoCode: "226",
        uniqueId: "equatorial_guinea_637996",
        flag: "https://flagcdn.com/w320/gq.png",
    },
    {
        name: "Eritrea",
        code: "ER",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+291",
        isoCode: "232",
        uniqueId: "eritrea_261492",
        flag: "https://flagcdn.com/w320/er.png",
    },
    {
        name: "Estonia",
        code: "EE",
        language: {
            code: "et",
            name: "Estonian",
        },
        dialling_code: "+372",
        isoCode: "233",
        uniqueId: "estonia_94330",
        flag: "https://flagcdn.com/w320/ee.png",
    },
    {
        name: "Ethiopia",
        code: "ET",
        language: {
            code: "am",
            name: "Amharic",
        },
        dialling_code: "+251",
        isoCode: "231",
        uniqueId: "ethiopia_972726",
        flag: "https://flagcdn.com/w320/et.png",
    },
    {
        name: "Falkland Islands (Malvinas)",
        code: "FK",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+500",
        isoCode: "238",
        uniqueId: "falkland_islands_(malvinas)_418707",
        flag: "https://flagcdn.com/w320/fk.png",
    },
    {
        name: "Faroe Islands",
        code: "FO",
        language: {
            code: "fo",
            name: "Faroese",
        },
        dialling_code: "+298",
        isoCode: "234",
        uniqueId: "faroe_islands_855178",
        flag: "https://flagcdn.com/w320/fo.png",
    },
    {
        name: "Fiji",
        code: "FJ",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+679",
        isoCode: "242",
        uniqueId: "fiji_678304",
        flag: "https://flagcdn.com/w320/fj.png",
    },
    {
        name: "Finland",
        code: "FI",
        language: {
            code: "fi",
            iso639_2: "fin",
            name: "Finnish",
            nativeName: "suomi",
        },
        dialling_code: "+358",
        isoCode: "246",
        uniqueId: "finland_671557",
        flag: "https://flagcdn.com/w320/fi.png",
    },
    {
        name: "France",
        code: "FR",
        demonym: "French",
        language: {
            code: "fr",
            name: "French",
        },
        dialling_code: "+33",
        isoCode: "250",
        uniqueId: "france_586539",
        flag: "https://flagcdn.com/w320/fr.png",
    },
    {
        name: "French Guiana",
        code: "GF",
        language: {
            code: "fr",
            name: "French",
        },
        dialling_code: "+594",
        isoCode: "254",
        uniqueId: "french_guiana_239010",
        flag: "https://flagcdn.com/w320/gf.png",
    },
    {
        name: "French Polynesia",
        code: "PF",
        language: {
            code: "fr",
            name: "French",
        },
        dialling_code: "+689",
        isoCode: "258",
        uniqueId: "french_polynesia_6249",
        flag: "https://flagcdn.com/w320/pf.png",
    },
    {
        name: "Gabon",
        code: "GA",
        language: {
            code: "fr",
            name: "French",
        },
        dialling_code: "+241",
        isoCode: "266",
        uniqueId: "gabon_909859",
        flag: "https://flagcdn.com/w320/ga.png",
    },
    {
        name: "Gambia",
        code: "GM",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+220",
        isoCode: "270",
        uniqueId: "gambia_384575",
        flag: "https://flagcdn.com/w320/gm.png",
    },
    {
        name: "Georgia",
        code: "GE",
        language: {
            code: "ka",
            name: "Georgian",
        },
        dialling_code: "+995",
        isoCode: "268",
        uniqueId: "georgia_225916",
        flag: "https://flagcdn.com/w320/ge.png",
    },
    {
        name: "Germany",
        code: "DE",
        language: {
            code: "de",
            name: "German",
        },
        dialling_code: "+49",
        isoCode: "276",
        uniqueId: "germany_454793",
        flag: "https://flagcdn.com/w320/de.png",
    },
    {
        name: "Ghana",
        code: "GH",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+233",
        isoCode: "288",
        uniqueId: "ghana_768863",
        flag: "https://flagcdn.com/w320/gh.png",
    },
    {
        name: "Gibraltar",
        code: "GI",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+350",
        isoCode: "292",
        uniqueId: "gibraltar_4658",
        flag: "https://flagcdn.com/w320/gi.png",
    },
    {
        name: "Greece",
        code: "GR",
        language: {
            code: "el",
            name: "Greek (modern)",
        },
        dialling_code: "+30",
        isoCode: "300",
        uniqueId: "greece_153713",
        flag: "https://flagcdn.com/w320/gr.png",
    },
    {
        name: "Greenland",
        code: "GL",
        language: {
            code: "kl",
            name: "Kalaallisut",
        },
        dialling_code: "+299",
        isoCode: "304",
        uniqueId: "greenland_293348",
        flag: "https://flagcdn.com/w320/gl.png",
    },
    {
        name: "Grenada",
        code: "GD",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+1",
        isoCode: "308",
        uniqueId: "grenada_430807",
        flag: "https://flagcdn.com/w320/gd.png",
    },
    {
        name: "Guadeloupe",
        code: "GP",
        language: {
            code: "fr",
            name: "French",
        },
        dialling_code: "+590",
        isoCode: "312",
        uniqueId: "guadeloupe_445322",
        flag: "https://flagcdn.com/w320/gp.png",
    },
    {
        name: "Guam",
        code: "GU",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+1",
        isoCode: "316",
        uniqueId: "guam_313761",
        flag: "https://flagcdn.com/w320/gu.png",
    },
    {
        name: "Guatemala",
        code: "GT",
        language: {
            code: "es",
            name: "Spanish",
        },
        dialling_code: "+502",
        isoCode: "320",
        uniqueId: "guatemala_727814",
        flag: "https://flagcdn.com/w320/gt.png",
    },
    {
        name: "Guinea",
        code: "GN",
        language: {
            code: "fr",
            name: "French",
        },
        dialling_code: "+224",
        isoCode: "324",
        uniqueId: "guinea_483739",
        flag: "https://flagcdn.com/w320/gn.png",
    },
    {
        name: "Guinea-Bissau",
        code: "GW",
        language: {
            code: "pt",
            name: "Portuguese",
        },
        dialling_code: "+245",
        isoCode: "624",
        uniqueId: "guinea-bissau_945606",
        flag: "https://flagcdn.com/w320/gw.png",
    },
    {
        name: "Guyana",
        code: "GY",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+592",
        isoCode: "328",
        uniqueId: "guyana_944736",
        flag: "https://flagcdn.com/w320/gy.png",
    },
    {
        name: "Haiti",
        code: "HT",
        language: {
            code: "fr",
            name: "French",
        },
        dialling_code: "+509",
        isoCode: "332",
        uniqueId: "haiti_193289",
        flag: "https://flagcdn.com/w320/ht.png",
    },
    {
        name: "Holy See",
        code: "VA",
        language: {
            code: "fr",
            name: "French",
        },
        dialling_code: "+39",
        isoCode: "336",
        uniqueId: "holy_see_817494",
        flag: "https://flagcdn.com/w320/va.png",
    },
    {
        name: "Honduras",
        code: "HN",
        language: {
            code: "es",
            name: "Spanish",
        },
        dialling_code: "+504",
        isoCode: "340",
        uniqueId: "honduras_933979",
        flag: "https://flagcdn.com/w320/hn.png",
    },
    {
        name: "Hong Kong",
        code: "HK",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+852",
        isoCode: "344",
        uniqueId: "hong_kong_811893",
        flag: "https://flagcdn.com/w320/hk.png",
    },
    {
        name: "Hungary",
        code: "HU",
        language: {
            code: "hu",
            name: "Hungarian",
        },
        dialling_code: "+36",
        isoCode: "348",
        uniqueId: "hungary_447433",
        flag: "https://flagcdn.com/w320/hu.png",
    },
    {
        name: "Iceland",
        code: "IS",
        language: {
            code: "is",
            name: "Icelandic",
        },
        dialling_code: "+354",
        isoCode: "352",
        uniqueId: "iceland_278040",
        flag: "https://flagcdn.com/w320/is.png",
    },
    {
        name: "India",
        code: "IN",
        language: {
            code: "hi",
            name: "Hindi",
        },
        dialling_code: "+91",
        isoCode: "356",
        uniqueId: "india_272876",
        flag: "https://flagcdn.com/w320/in.png",
    },
    {
        name: "Indonesia",
        code: "ID",
        language: {
            code: "id",
            name: "Indonesian",
        },
        dialling_code: "+62",
        isoCode: "360",
        uniqueId: "indonesia_680936",
        flag: "https://flagcdn.com/w320/id.png",
    },
    {
        name: "Côte d'Ivoire",
        code: "CI",
        language: {
            code: "fr",
            name: "French",
        },
        dialling_code: "+225",
        isoCode: "384",
        uniqueId: "côte_d'ivoire_695980",
        flag: "https://flagcdn.com/w320/ci.png",
    },
    {
        name: "Iran (Islamic Republic of)",
        code: "IR",
        language: {
            code: "fa",
            name: "Persian (Farsi)",
        },
        dialling_code: "+98",
        isoCode: "364",
        uniqueId: "iran_(islamic_republic_of)_229980",
        flag: "https://flagcdn.com/w320/ir.png",
    },
    {
        name: "Iraq",
        code: "IQ",
        language: {
            code: "ar",
            name: "Arabic",
        },
        dialling_code: "+964",
        isoCode: "368",
        uniqueId: "iraq_804914",
        flag: "https://flagcdn.com/w320/iq.png",
    },
    {
        name: "Ireland",
        code: "IE",
        language: {
            code: "ga",
            name: "Irish",
        },
        dialling_code: "+353",
        isoCode: "372",
        uniqueId: "ireland_902619",
        flag: "https://flagcdn.com/w320/ie.png",
    },
    {
        name: "Israel",
        code: "IL",
        language: {
            code: "he",
            name: "Hebrew (modern)",
        },
        dialling_code: "+972",
        isoCode: "376",
        uniqueId: "israel_628121",
        flag: "https://flagcdn.com/w320/il.png",
    },
    {
        name: "Italy",
        code: "IT",
        language: {
            code: "it",
            name: "Italian",
        },
        dialling_code: "+39",
        isoCode: "380",
        uniqueId: "italy_247004",
        flag: "https://flagcdn.com/w320/it.png",
    },
    {
        name: "Jamaica",
        code: "JM",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+1",
        isoCode: "388",
        uniqueId: "jamaica_742391",
        flag: "https://flagcdn.com/w320/jm.png",
    },
    {
        name: "Japan",
        code: "JP",
        language: {
            code: "ja",
            name: "Japanese",
        },
        dialling_code: "+81",
        isoCode: "392",
        uniqueId: "japan_450018",
        flag: "https://flagcdn.com/w320/jp.png",
    },
    {
        name: "Jordan",
        code: "JO",
        language: {
            code: "ar",
            name: "Arabic",
        },
        dialling_code: "+962",
        isoCode: "400",
        uniqueId: "jordan_417416",
        flag: "https://flagcdn.com/w320/jo.png",
    },
    {
        name: "Kazakhstan",
        code: "KZ",
        language: {
            code: "kk",
            name: "Kazakh",
        },
        dialling_code: "+7",
        isoCode: "398",
        uniqueId: "kazakhstan_372819",
        flag: "https://flagcdn.com/w320/kz.png",
    },
    {
        name: "Kenya",
        code: "KE",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+254",
        isoCode: "404",
        uniqueId: "kenya_643256",
        flag: "https://flagcdn.com/w320/ke.png",
    },
    {
        name: "Kiribati",
        code: "KI",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+686",
        isoCode: "296",
        uniqueId: "kiribati_984299",
        flag: "https://flagcdn.com/w320/ki.png",
    },
    {
        name: "Kuwait",
        code: "KW",
        language: {
            code: "ar",
            name: "Arabic",
        },
        dialling_code: "+965",
        isoCode: "414",
        uniqueId: "kuwait_388362",
        flag: "https://flagcdn.com/w320/kw.png",
    },
    {
        name: "Kyrgyzstan",
        code: "KG",
        language: {
            code: "ky",
            name: "Kyrgyz",
        },
        dialling_code: "+996",
        isoCode: "417",
        uniqueId: "kyrgyzstan_665595",
        flag: "https://flagcdn.com/w320/kg.png",
    },
    {
        name: "Lao People's Democratic Republic",
        code: "LA",
        language: {
            code: "lo",
            name: "Lao",
        },
        dialling_code: "+856",
        isoCode: "418",
        uniqueId: "lao_people's_democratic_republic_54262",
        flag: "https://flagcdn.com/w320/la.png",
    },
    {
        name: "Latvia",
        code: "LV",
        language: {
            code: "lv",
            name: "Latvian",
        },
        dialling_code: "+371",
        isoCode: "428",
        uniqueId: "latvia_605064",
        flag: "https://flagcdn.com/w320/lv.png",
    },
    {
        name: "Lebanon",
        code: "LB",
        language: {
            code: "ar",
            name: "Arabic",
        },
        dialling_code: "+961",
        isoCode: "422",
        uniqueId: "lebanon_523636",
        flag: "https://flagcdn.com/w320/lb.png",
    },
    {
        name: "Lesotho",
        code: "LS",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+266",
        isoCode: "426",
        uniqueId: "lesotho_169228",
        flag: "https://flagcdn.com/w320/ls.png",
    },
    {
        name: "Liberia",
        code: "LR",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+231",
        isoCode: "430",
        uniqueId: "liberia_497922",
        flag: "https://flagcdn.com/w320/lr.png",
    },
    {
        name: "Libya",
        code: "LY",
        language: {
            code: "ar",
            name: "Arabic",
        },
        dialling_code: "+218",
        isoCode: "434",
        uniqueId: "libya_571086",
        flag: "https://flagcdn.com/w320/ly.png",
    },
    {
        name: "Liechtenstein",
        code: "LI",
        language: {
            code: "de",
            name: "German",
        },
        dialling_code: "+423",
        isoCode: "438",
        uniqueId: "liechtenstein_933153",
        flag: "https://flagcdn.com/w320/li.png",
    },
    {
        name: "Lithuania",
        code: "LT",
        language: {
            code: "lt",
            name: "Lithuanian",
        },
        dialling_code: "+370",
        isoCode: "440",
        uniqueId: "lithuania_375351",
        flag: "https://flagcdn.com/w320/lt.png",
    },
    {
        name: "Luxembourg",
        code: "LU",
        language: {
            code: "fr",
            name: "French",
        },
        dialling_code: "+352",
        isoCode: "442",
        uniqueId: "luxembourg_724701",
        flag: "https://flagcdn.com/w320/lu.png",
    },
    {
        name: "Macao",
        code: "MO",
        language: {
            code: "zh",
            name: "Chinese",
        },
        dialling_code: "+853",
        isoCode: "446",
        uniqueId: "macao_724121",
        flag: "https://flagcdn.com/w320/mo.png",
    },
    {
        name: "Macedonia",
        code: "MK",
        language: {
            code: "mk",
            name: "Macedonian",
        },
        dialling_code: "+389",
        isoCode: "807",
        uniqueId: "macedonia_(the_former_yugoslav_republic_of)_748008",
        flag: "https://flagcdn.com/w320/mk.png",
    },
    {
        name: "Madagascar",
        code: "MG",
        language: {
            code: "fr",
            name: "French",
        },
        dialling_code: "+261",
        isoCode: "450",
        uniqueId: "madagascar_837042",
        flag: "https://flagcdn.com/w320/mg.png",
    },
    {
        name: "Malawi",
        code: "MW",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+265",
        isoCode: "454",
        uniqueId: "malawi_881673",
        flag: "https://flagcdn.com/w320/mw.png",
    },
    {
        name: "Malaysia",
        code: "MY",
        language: {
            code: null,
            name: "Malaysian",
        },
        dialling_code: "+60",
        isoCode: "458",
        uniqueId: "malaysia_844272",
        flag: "https://flagcdn.com/w320/my.png",
    },
    {
        name: "Maldives",
        code: "MV",
        language: {
            code: "dv",
            name: "Divehi",
        },
        dialling_code: "+960",
        isoCode: "462",
        uniqueId: "maldives_846585",
        flag: "https://flagcdn.com/w320/mv.png",
    },
    {
        name: "Mali",
        code: "ML",
        language: {
            code: "fr",
            name: "French",
        },
        dialling_code: "+223",
        isoCode: "466",
        uniqueId: "mali_766502",
        flag: "https://flagcdn.com/w320/ml.png",
    },
    {
        name: "Malta",
        code: "MT",
        language: {
            code: "mt",
            name: "Maltese",
        },
        dialling_code: "+356",
        isoCode: "470",
        uniqueId: "malta_618251",
        flag: "https://flagcdn.com/w320/mt.png",
    },
    {
        name: "Marshall Islands",
        code: "MH",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+692",
        isoCode: "584",
        uniqueId: "marshall_islands_426253",
        flag: "https://flagcdn.com/w320/mh.png",
    },
    {
        name: "Martinique",
        code: "MQ",
        language: {
            code: "fr",
            name: "French",
        },
        dialling_code: "+596",
        isoCode: "474",
        uniqueId: "martinique_919263",
        flag: "https://flagcdn.com/w320/mq.png",
    },
    {
        name: "Mauritania",
        code: "MR",
        language: {
            code: "ar",
            name: "Arabic",
        },
        dialling_code: "+222",
        isoCode: "478",
        uniqueId: "mauritania_846724",
        flag: "https://flagcdn.com/w320/mr.png",
    },
    {
        name: "Mauritius",
        code: "MU",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+230",
        isoCode: "480",
        uniqueId: "mauritius_228531",
        flag: "https://flagcdn.com/w320/mu.png",
    },
    {
        name: "Mayotte",
        code: "YT",
        language: {
            code: "fr",
            name: "French",
        },
        dialling_code: "+262",
        isoCode: "175",
        uniqueId: "mayotte_913844",
        flag: "https://flagcdn.com/w320/yt.png",
    },
    {
        name: "Mexico",
        code: "MX",
        language: {
            code: "es",
            name: "Spanish",
        },
        dialling_code: "+52",
        isoCode: "484",
        uniqueId: "mexico_458432",
        flag: "https://flagcdn.com/w320/mx.png",
    },
    {
        name: "Micronesia (Federated States of)",
        code: "FM",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+691",
        isoCode: "583",
        uniqueId: "micronesia_(federated_states_of)_551696",
        flag: "https://flagcdn.com/w320/fm.png",
    },
    {
        name: "Moldova (Republic of)",
        code: "MD",
        language: {
            code: "ro",
            name: "Romanian",
        },
        dialling_code: "+373",
        isoCode: "498",
        uniqueId: "moldova_(republic_of)_931411",
        flag: "https://flagcdn.com/w320/md.png",
    },
    {
        name: "Monaco",
        code: "MC",
        language: {
            code: "fr",
            name: "French",
        },
        dialling_code: "+377",
        isoCode: "492",
        uniqueId: "monaco_100501",
        flag: "https://flagcdn.com/w320/mc.png",
    },
    {
        name: "Mongolia",
        code: "MN",
        language: {
            code: "mn",
            name: "Mongolian",
        },
        dialling_code: "+976",
        isoCode: "496",
        uniqueId: "mongolia_898189",
        flag: "https://flagcdn.com/w320/mn.png",
    },
    {
        name: "Montenegro",
        code: "ME",
        language: {
            code: "sr",
            name: "Serbian",
        },
        dialling_code: "+382",
        isoCode: "499",
        uniqueId: "montenegro_892471",
        flag: "https://flagcdn.com/w320/me.png",
    },
    {
        name: "Montserrat",
        code: "MS",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+1",
        isoCode: "500",
        uniqueId: "montserrat_709153",
        flag: "https://flagcdn.com/w320/ms.png",
    },
    {
        name: "Morocco",
        code: "MA",
        language: {
            code: "ar",
            name: "Arabic",
        },
        dialling_code: "+212",
        isoCode: "504",
        uniqueId: "morocco_138757",
        flag: "https://flagcdn.com/w320/ma.png",
    },
    {
        name: "Mozambique",
        code: "MZ",
        language: {
            code: "pt",
            name: "Portuguese",
        },
        dialling_code: "+258",
        isoCode: "508",
        uniqueId: "mozambique_501490",
        flag: "https://flagcdn.com/w320/mz.png",
    },
    {
        name: "Myanmar",
        code: "MM",
        language: {
            code: "my",
            name: "Burmese",
        },
        dialling_code: "+95",
        isoCode: "104",
        uniqueId: "myanmar_48701",
        flag: "https://flagcdn.com/w320/mm.png",
    },
    {
        name: "Namibia",
        code: "NA",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+264",
        isoCode: "516",
        uniqueId: "namibia_537571",
        flag: "https://flagcdn.com/w320/na.png",
    },
    {
        name: "Nauru",
        code: "NR",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+674",
        isoCode: "520",
        uniqueId: "nauru_930030",
        flag: "https://flagcdn.com/w320/nr.png",
    },
    {
        name: "Nepal",
        code: "NP",
        language: {
            code: "ne",
            name: "Nepali",
        },
        dialling_code: "+977",
        isoCode: "524",
        uniqueId: "nepal_670490",
        flag: "https://flagcdn.com/w320/np.png",
    },
    {
        name: "Netherlands",
        code: "NL",
        language: {
            code: "nl",
            name: "Dutch",
        },
        dialling_code: "+31",
        isoCode: "528",
        uniqueId: "netherlands_886329",
        flag: "https://flagcdn.com/w320/nl.png",
    },
    {
        name: "New Caledonia",
        code: "NC",
        language: {
            code: "fr",
            name: "French",
        },
        dialling_code: "+687",
        isoCode: "540",
        uniqueId: "new_caledonia_399790",
        flag: "https://flagcdn.com/w320/nc.png",
    },
    {
        name: "New Zealand",
        code: "NZ",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+64",
        isoCode: "554",
        uniqueId: "new_zealand_452464",
        flag: "https://flagcdn.com/w320/nz.png",
    },
    {
        name: "Nicaragua",
        code: "NI",
        language: {
            code: "es",
            name: "Spanish",
        },
        dialling_code: "+505",
        isoCode: "558",
        uniqueId: "nicaragua_38754",
        flag: "https://flagcdn.com/w320/ni.png",
    },
    {
        name: "Niger",
        code: "NE",
        language: {
            code: "fr",
            name: "French",
        },
        dialling_code: "+227",
        isoCode: "562",
        uniqueId: "niger_444785",
        flag: "https://flagcdn.com/w320/ne.png",
    },
    {
        name: "Nigeria",
        code: "NG",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+234",
        isoCode: "566",
        uniqueId: "nigeria_175972",
        flag: "https://flagcdn.com/w320/ng.png",
    },
    {
        name: "Niue",
        code: "NU",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+683",
        isoCode: "570",
        uniqueId: "niue_209896",
        flag: "https://flagcdn.com/w320/nu.png",
    },
    {
        name: "Norfolk Island",
        code: "NF",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+672",
        isoCode: "574",
        uniqueId: "norfolk_island_159014",
        flag: "https://flagcdn.com/w320/nf.png",
    },
    {
        name: "Korea (Democratic People's Republic of)",
        code: "KP",
        language: {
            code: "ko",
            name: "Korean",
        },
        dialling_code: "+850",
        isoCode: "408",
        uniqueId: "korea_(democratic_people's_republic_of)_80809",
        flag: "https://flagcdn.com/w320/kp.png",
    },
    {
        name: "Northern Mariana Islands",
        code: "MP",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+1",
        isoCode: "580",
        uniqueId: "northern_mariana_islands_63432",
        flag: "https://flagcdn.com/w320/mp.png",
    },
    {
        name: "Norway",
        code: "NO",
        language: {
            code: "no",
            name: "Norwegian",
        },
        dialling_code: "+47",
        isoCode: "578",
        uniqueId: "norway_168728",
        flag: "https://flagcdn.com/w320/no.png",
    },
    {
        name: "Oman",
        code: "OM",
        language: {
            code: "ar",
            name: "Arabic",
        },
        dialling_code: "+968",
        isoCode: "512",
        uniqueId: "oman_322157",
        flag: "https://flagcdn.com/w320/om.png",
    },
    {
        name: "Pakistan",
        code: "PK",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+92",
        isoCode: "586",
        uniqueId: "pakistan_863777",
        flag: "https://flagcdn.com/w320/pk.png",
    },
    {
        name: "Palau",
        code: "PW",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+680",
        isoCode: "585",
        uniqueId: "palau_5344",
        flag: "https://flagcdn.com/w320/pw.png",
    },
    {
        name: "Palestine, State of",
        code: "PS",
        language: {
            code: "ar",
            name: "Arabic",
        },
        dialling_code: "+970",
        isoCode: "275",
        uniqueId: "palestine,_state_of_715255",
        flag: "https://flagcdn.com/w320/ps.png",
    },
    {
        name: "Panama",
        code: "PA",
        language: {
            code: "es",
            name: "Spanish",
        },
        dialling_code: "+507",
        isoCode: "591",
        uniqueId: "panama_595547",
        flag: "https://flagcdn.com/w320/pa.png",
    },
    {
        name: "Papua New Guinea",
        code: "PG",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+675",
        isoCode: "598",
        uniqueId: "papua_new_guinea_430554",
        flag: "https://flagcdn.com/w320/pg.png",
    },
    {
        name: "Paraguay",
        code: "PY",
        language: {
            code: "es",
            name: "Spanish",
        },
        dialling_code: "+595",
        isoCode: "600",
        uniqueId: "paraguay_695276",
        flag: "https://flagcdn.com/w320/py.png",
    },
    {
        name: "Peru",
        code: "PE",
        language: {
            code: "es",
            name: "Spanish",
        },
        dialling_code: "+51",
        isoCode: "604",
        uniqueId: "peru_782678",
        flag: "https://flagcdn.com/w320/pe.png",
    },
    {
        name: "Philippines",
        code: "PH",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+63",
        isoCode: "608",
        uniqueId: "philippines_193475",
        flag: "https://flagcdn.com/w320/ph.png",
    },
    {
        name: "Poland",
        code: "PL",
        language: {
            code: "pl",
            name: "Polish",
        },
        dialling_code: "+48",
        isoCode: "616",
        uniqueId: "poland_392376",
        flag: "https://flagcdn.com/w320/pl.png",
    },
    {
        name: "Portugal",
        code: "PT",
        language: {
            code: "pt",
            name: "Portuguese",
        },
        dialling_code: "+351",
        isoCode: "620",
        uniqueId: "portugal_680334",
        flag: "https://flagcdn.com/w320/pt.png",
    },
    {
        name: "Puerto Rico",
        code: "PR",
        language: {
            code: "es",
            name: "Spanish",
        },
        dialling_code: "+1",
        isoCode: "630",
        uniqueId: "puerto_rico_742158",
        flag: "https://flagcdn.com/w320/pr.png",
    },
    {
        name: "Qatar",
        code: "QA",
        language: {
            code: "ar",
            name: "Arabic",
        },
        dialling_code: "+974",
        isoCode: "634",
        uniqueId: "qatar_158016",
        flag: "https://flagcdn.com/w320/qa.png",
    },
    {
        name: "Republic of Kosovo",
        code: "XK",
        language: {
            code: "sq",
            name: "Albanian",
        },
        dialling_code: "+381",
        isoCode: "383",
        uniqueId: "republic_of_kosovo_145665",
        flag: "https://flagcdn.com/w320/xk.png",
    },
    {
        name: "Réunion",
        code: "RE",
        language: {
            code: "fr",
            name: "French",
        },
        dialling_code: "+262",
        isoCode: "638",
        uniqueId: "réunion_494781",
        flag: "https://flagcdn.com/w320/re.png",
    },
    {
        name: "Romania",
        code: "RO",
        language: {
            code: "ro",
            name: "Romanian",
        },
        dialling_code: "+40",
        isoCode: "642",
        uniqueId: "romania_305614",
        flag: "https://flagcdn.com/w320/ro.png",
    },
    {
        name: "Russian Federation",
        code: "RU",
        language: {
            code: "ru",
            name: "Russian",
        },
        dialling_code: "+7",
        isoCode: "643",
        uniqueId: "russian_federation_888306",
        flag: "https://flagcdn.com/w320/ru.png",
    },
    {
        name: "Rwanda",
        code: "RW",
        language: {
            code: "rw",
            name: "Kinyarwanda",
        },
        dialling_code: "+250",
        isoCode: "646",
        uniqueId: "rwanda_738461",
        flag: "https://flagcdn.com/w320/rw.png",
    },
    {
        name: "Saint Barthélemy",
        code: "BL",
        language: {
            code: "fr",
            name: "French",
        },
        dialling_code: "+590",
        isoCode: "652",
        uniqueId: "saint_barthélemy_908492",
        flag: "https://flagcdn.com/w320/bl.png",
    },
    {
        name: "Saint Helena, Ascension and Tristan da Cunha",
        code: "SH",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+290",
        isoCode: "654",
        uniqueId: "saint_helena,_ascension_and_tristan_da_cunha_647893",
        flag: "https://flagcdn.com/w320/sh.png",
    },
    {
        name: "Saint Kitts and Nevis",
        code: "KN",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+1",
        isoCode: "659",
        uniqueId: "saint_kitts_and_nevis_556794",
        flag: "https://flagcdn.com/w320/kn.png",
    },
    {
        name: "Saint Lucia",
        code: "LC",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+1",
        isoCode: "662",
        uniqueId: "saint_lucia_603137",
        flag: "https://flagcdn.com/w320/lc.png",
    },
    {
        name: "Saint Martin (French part)",
        code: "MF",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+590",
        isoCode: "663",
        uniqueId: "saint_martin_(french_part)_752572",
        flag: "https://flagcdn.com/w320/mf.png",
    },
    {
        name: "Saint Pierre and Miquelon",
        code: "PM",
        language: {
            code: "fr",
            name: "French",
        },
        dialling_code: "+508",
        isoCode: "666",
        uniqueId: "saint_pierre_and_miquelon_651575",
        flag: "https://flagcdn.com/w320/pm.png",
    },
    {
        name: "Saint Vincent and the Grenadines",
        code: "VC",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+1",
        isoCode: "670",
        uniqueId: "saint_vincent_and_the_grenadines_716082",
        flag: "https://flagcdn.com/w320/vc.png",
    },
    {
        name: "Samoa",
        code: "WS",
        language: {
            code: "sm",
            name: "Samoan",
        },
        dialling_code: "+685",
        isoCode: "882",
        uniqueId: "samoa_59323",
        flag: "https://flagcdn.com/w320/ws.png",
    },
    {
        name: "San Marino",
        code: "SM",
        language: {
            code: "it",
            name: "Italian",
        },
        dialling_code: "+378",
        isoCode: "674",
        uniqueId: "san_marino_806584",
        flag: "https://flagcdn.com/w320/sm.png",
    },
    {
        name: "Sao Tome and Principe",
        code: "ST",
        language: {
            code: "pt",
            name: "Portuguese",
        },
        dialling_code: "+239",
        isoCode: "678",
        uniqueId: "sao_tome_and_principe_437447",
        flag: "https://flagcdn.com/w320/st.png",
    },
    {
        name: "Saudi Arabia",
        code: "SA",
        language: {
            code: "ar",
            name: "Arabic",
        },
        dialling_code: "+966",
        isoCode: "682",
        uniqueId: "saudi_arabia_944587",
        flag: "https://flagcdn.com/w320/sa.png",
    },
    {
        name: "Senegal",
        code: "SN",
        language: {
            code: "fr",
            name: "French",
        },
        dialling_code: "+221",
        isoCode: "686",
        uniqueId: "senegal_142743",
        flag: "https://flagcdn.com/w320/sn.png",
    },
    {
        name: "Serbia",
        code: "RS",
        language: {
            code: "sr",
            name: "Serbian",
        },
        dialling_code: "+381",
        isoCode: "688",
        uniqueId: "serbia_704889",
        flag: "https://flagcdn.com/w320/rs.png",
    },
    {
        name: "Seychelles",
        code: "SC",
        language: {
            code: "fr",
            name: "French",
        },
        dialling_code: "+248",
        isoCode: "690",
        uniqueId: "seychelles_829127",
        flag: "https://flagcdn.com/w320/sc.png",
    },
    {
        name: "Sierra Leone",
        code: "SL",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+232",
        isoCode: "694",
        uniqueId: "sierra_leone_568059",
        flag: "https://flagcdn.com/w320/sl.png",
    },
    {
        name: "Singapore",
        code: "SG",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+65",
        isoCode: "702",
        uniqueId: "singapore_49866",
        flag: "https://flagcdn.com/w320/sg.png",
    },
    {
        name: "Singapore",
        code: "SG",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+65",
        isoCode: "702",
        uniqueId: "singapore_39402",
        flag: "https://flagcdn.com/w320/sg.png",
    },
    {
        name: "Slovakia",
        code: "SK",
        language: {
            code: "sk",
            name: "Slovak",
        },
        dialling_code: "+421",
        isoCode: "703",
        uniqueId: "slovakia_747023",
        flag: "https://flagcdn.com/w320/sk.png",
    },
    {
        name: "Slovenia",
        code: "SI",
        language: {
            code: "sl",
            name: "Slovene",
        },
        dialling_code: "+386",
        isoCode: "705",
        uniqueId: "slovenia_22787",
        flag: "https://flagcdn.com/w320/si.png",
    },
    {
        name: "Solomon Islands",
        code: "SB",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+677",
        isoCode: "090",
        uniqueId: "solomon_islands_207060",
        flag: "https://flagcdn.com/w320/sb.png",
    },
    {
        name: "Somalia",
        code: "SO",
        language: {
            code: "ar",
            name: "Arabic",
        },
        dialling_code: "+252",
        isoCode: "706",
        uniqueId: "somalia_374589",
        flag: "https://flagcdn.com/w320/so.png",
    },
    {
        name: "South Africa",
        code: "ZA",
        language: {
            code: "en",
            iso639_2: "eng",
            name: "English",
            nativeName: "English",
        },
        dialling_code: "+27",
        isoCode: "710",
        uniqueId: "south_africa_831819",
        flag: "https://flagcdn.com/w320/za.png",
    },
    {
        name: "Korea (Republic of)",
        code: "KR",
        language: {
            code: "ko",
            name: "Korean",
        },
        dialling_code: "+82",
        isoCode: "410",
        uniqueId: "korea_(republic_of)_526179",
        flag: "https://flagcdn.com/w320/kr.png",
    },
    {
        name: "Spain",
        code: "ES",
        language: {
            code: "es",
            name: "Spanish",
        },
        dialling_code: "+34",
        isoCode: "724",
        uniqueId: "spain_912735",
        flag: "https://flagcdn.com/w320/es.png",
    },
    {
        name: "Sri Lanka",
        code: "LK",
        language: {
            code: "si",
            iso639_2: "sin",
            name: "Sinhalese",
            nativeName: "සිංහල",
        },
        dialling_code: "+94",
        isoCode: "144",
        uniqueId: "sri_lanka_176473",
        flag: "https://flagcdn.com/w320/lk.png",
    },
    {
        name: "Sudan",
        code: "SD",
        language: {
            code: "ar",
            name: "Arabic",
        },
        dialling_code: "+249",
        isoCode: "729",
        uniqueId: "sudan_909460",
        flag: "https://flagcdn.com/w320/sd.png",
    },
    {
        name: "Suriname",
        code: "SR",
        language: {
            code: "nl",
            name: "Dutch",
        },
        dialling_code: "+597",
        isoCode: "740",
        uniqueId: "suriname_852145",
        flag: "https://flagcdn.com/w320/sr.png",
    },
    {
        name: "Swaziland",
        code: "SZ",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+268",
        isoCode: "748",
        uniqueId: "swaziland_820056",
        flag: "https://flagcdn.com/w320/sz.png",
    },
    {
        name: "Sweden",
        code: "SE",
        language: {
            code: "sv",
            name: "Swedish",
        },
        dialling_code: "+46",
        isoCode: "752",
        uniqueId: "sweden_158658",
        flag: "https://flagcdn.com/w320/se.png",
    },
    {
        name: "Switzerland",
        code: "CH",
        language: {
            code: "de",
            name: "German",
        },
        dialling_code: "+41",
        isoCode: "756",
        uniqueId: "switzerland_608357",
        flag: "https://flagcdn.com/w320/ch.png",
    },
    {
        name: "Syrian Arab Republic",
        code: "SY",
        language: {
            code: "ar",
            name: "Arabic",
        },
        dialling_code: "+963",
        isoCode: "760",
        uniqueId: "syrian_arab_republic_745639",
        flag: "https://flagcdn.com/w320/sy.png",
    },
    {
        name: "Taiwan",
        code: "TW",
        language: {
            code: "zh",
            name: "Chinese",
        },
        dialling_code: "+886",
        isoCode: "158",
        uniqueId: "taiwan_770433",
        flag: "https://flagcdn.com/w320/tw.png",
    },
    {
        name: "Tajikistan",
        code: "TJ",
        language: {
            code: "tg",
            name: "Tajik",
        },
        dialling_code: "+992",
        isoCode: "762",
        uniqueId: "tajikistan_54092",
        flag: "https://flagcdn.com/w320/tj.png",
    },
    {
        name: "Tanzania, United Republic of",
        code: "TZ",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+255",
        isoCode: "834",
        uniqueId: "tanzania,_united_republic_of_987351",
        flag: "https://flagcdn.com/w320/tz.png",
    },
    {
        name: "Thailand",
        code: "TH",
        language: {
            code: "th",
            name: "Thai",
        },
        dialling_code: "+66",
        isoCode: "764",
        uniqueId: "thailand_959431",
        flag: "https://flagcdn.com/w320/th.png",
    },
    {
        name: "Timor-Leste",
        code: "TL",
        language: {
            code: "pt",
            name: "Portuguese",
        },
        dialling_code: "+670",
        isoCode: "626",
        uniqueId: "timor-leste_957008",
        flag: "https://flagcdn.com/w320/tl.png",
    },
    {
        name: "Togo",
        code: "TG",
        language: {
            code: "fr",
            name: "French",
        },
        dialling_code: "+228",
        isoCode: "768",
        uniqueId: "togo_907822",
        flag: "https://flagcdn.com/w320/tg.png",
    },
    {
        name: "Tokelau",
        code: "TK",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+690",
        isoCode: "772",
        uniqueId: "tokelau_681273",
        flag: "https://flagcdn.com/w320/tk.png",
    },
    {
        name: "Tonga",
        code: "TO",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+676",
        isoCode: "776",
        uniqueId: "tonga_206248",
        flag: "https://flagcdn.com/w320/to.png",
    },
    {
        name: "Trinidad and Tobago",
        code: "TT",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+1",
        isoCode: "780",
        uniqueId: "trinidad_and_tobago_383036",
        flag: "https://flagcdn.com/w320/tt.png",
    },
    {
        name: "Tunisia",
        code: "TN",
        language: {
            code: "ar",
            name: "Arabic",
        },
        dialling_code: "+216",
        isoCode: "788",
        uniqueId: "tunisia_119445",
        flag: "https://flagcdn.com/w320/tn.png",
    },
    {
        name: "Turkey",
        code: "TR",
        language: {
            code: "tr",
            name: "Turkish",
        },
        dialling_code: "+90",
        isoCode: "792",
        uniqueId: "turkey_706610",
        flag: "https://flagcdn.com/w320/tr.png",
    },
    {
        name: "Turkmenistan",
        code: "TM",
        language: {
            code: "tk",
            name: "Turkmen",
        },
        dialling_code: "+993",
        isoCode: "795",
        uniqueId: "turkmenistan_546829",
        flag: "https://flagcdn.com/w320/tm.png",
    },
    {
        name: "Turks and Caicos Islands",
        code: "TC",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+1",
        isoCode: "796",
        uniqueId: "turks_and_caicos_islands_279503",
        flag: "https://flagcdn.com/w320/tc.png",
    },
    {
        name: "Tuvalu",
        code: "TV",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+688",
        isoCode: "798",
        uniqueId: "tuvalu_92644",
        flag: "https://flagcdn.com/w320/tv.png",
    },
    {
        name: "Uganda",
        code: "UG",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+256",
        isoCode: "800",
        uniqueId: "uganda_499821",
        flag: "https://flagcdn.com/w320/ug.png",
    },
    {
        name: "Ukraine",
        code: "UA",
        language: {
            code: "uk",
            name: "Ukrainian",
        },
        dialling_code: "+380",
        isoCode: "804",
        uniqueId: "ukraine_450630",
        flag: "https://flagcdn.com/w320/ua.png",
    },
    {
        name: "United Arab Emirates",
        code: "AE",
        language: {
            code: "ar",
            name: "Arabic",
        },
        dialling_code: "+971",
        isoCode: "784",
        uniqueId: "united_arab_emirates_47208",
        flag: "https://flagcdn.com/w320/ae.png",
    },
    {
        name: "Uruguay",
        code: "UY",
        language: {
            code: "es",
            name: "Spanish",
        },
        dialling_code: "+598",
        isoCode: "858",
        uniqueId: "uruguay_937723",
        flag: "https://flagcdn.com/w320/uy.png",
    },
    {
        name: "Uzbekistan",
        code: "UZ",
        language: {
            code: "uz",
            name: "Uzbek",
        },
        dialling_code: "+998",
        isoCode: "860",
        uniqueId: "uzbekistan_190105",
        flag: "https://flagcdn.com/w320/uz.png",
    },
    {
        name: "Vanuatu",
        code: "VU",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+678",
        isoCode: "548",
        uniqueId: "vanuatu_26244",
        flag: "https://flagcdn.com/w320/vu.png",
    },
    {
        name: "Venezuela (Bolivarian Republic of)",
        code: "VE",
        language: {
            code: "es",
            name: "Spanish",
        },
        dialling_code: "+58",
        isoCode: "862",
        uniqueId: "venezuela_(bolivarian_republic_of)_706504",
        flag: "https://flagcdn.com/w320/ve.png",
    },
    {
        name: "Viet Nam",
        code: "VN",
        language: {
            code: "vi",
            name: "Vietnamese",
        },
        dialling_code: "+84",
        isoCode: "704",
        uniqueId: "viet_nam_914962",
        flag: "https://flagcdn.com/w320/vn.png",
    },
    {
        name: "Wallis and Futuna",
        code: "WF",
        language: {
            code: "fr",
            name: "French",
        },
        dialling_code: "+681",
        isoCode: "876",
        uniqueId: "wallis_and_futuna_232189",
        flag: "https://flagcdn.com/w320/wf.png",
    },
    {
        name: "Wallis and Futuna",
        code: "WF",
        language: {
            code: "fr",
            name: "French",
        },
        dialling_code: "+681",
        isoCode: "876",
        uniqueId: "wallis_and_futuna_837817",
        flag: "https://flagcdn.com/w320/wf.png",
    },
    {
        name: "Yemen",
        code: "YE",
        language: {
            code: "ar",
            name: "Arabic",
        },
        dialling_code: "+967",
        isoCode: "887",
        uniqueId: "yemen_149410",
        flag: "https://flagcdn.com/w320/ye.png",
    },
    {
        name: "Zambia",
        code: "ZM",
        language: {
            code: "en",
            name: "English",
        },
        dialling_code: "+260",
        isoCode: "894",
        uniqueId: "zambia_711406",
        flag: "https://flagcdn.com/w320/zm.png",
    },
    {
        name: "Zimbabwe",
        code: "ZW",
        language: {
            code: "en",
            iso639_2: "eng",
            name: "English",
            nativeName: "English",
        },
        dialling_code: "+263",
        isoCode: "716",
        uniqueId: "zimbabwe_113641",
        flag: "https://flagcdn.com/w320/zw.png",
    },
];
