export const FavoriteSchoolData = [
  {
    id: "1",
    name: "The Manchester School",
    caption: "250+ Cources",
    image: require("@/assets/images/studentHomePage/courseImages/course-1.png"),
    favorite: true,
  },
  {
    id: "2",
    name: "Henley Business School",
    caption: "250+ Cources",
    image: require("@/assets/images/studentHomePage/courseImages/course-1.png"),
    favorite: true,
  },
  {
    id: "3",
    name: "The Manchester School",
    caption: "250+ Cources",
    image: require("@/assets/images/studentHomePage/courseImages/course-1.png"),
    favorite: true,
  },
  {
    id: "4",
    name: "Henley Business School",
    caption: "250+ Cources",
    image: require("@/assets/images/studentHomePage/courseImages/course-1.png"),
    favorite: true,
  },
  {
    id: "1",
    name: "The Manchester School",
    caption: "250+ Cources",
    image: require("@/assets/images/studentHomePage/courseImages/course-1.png"),
    favorite: true,
  },
  {
    id: "2",
    name: "Henley Business School",
    caption: "250+ Cources",
    image: require("@/assets/images/studentHomePage/courseImages/course-1.png"),
    favorite: true,
  },
  {
    id: "3",
    name: "The Manchester School",
    caption: "250+ Cources",
    image: require("@/assets/images/studentHomePage/courseImages/course-1.png"),
    favorite: true,
  },
  {
    id: "4",
    name: "Henley Business School",
    caption: "250+ Cources",
    image: require("@/assets/images/studentHomePage/courseImages/course-1.png"),
    favorite: true,
  },
];
